### ISSUE TITLE
Add support for WebRTC

### ISSUE THREAD

**Issue by ekryski** [feathersjs-ecosystem/feathers-sync#19]
I'm not even sure if this is possible but creating a mesh network of peer-to-peer nodes using WebRTC or something similar would be amazeballs. This would make things very fault tolerant and remove the need to run another service for the synchronization.

Less moving parts equals more better!!

**Comment by ramsestom** [comment]
Another option would be to simply implement it as a private feathers service (not exposed to real users) using websocket connections (with socket.io or primus) where each node would be a 'client' of the others that would be listening for some synchronization message (a messages containing the event that need to be propagated).
The only drawback I see is that it would (slightly) increase the number of connections on each node (if you have 50 nodes, each node will have 49 new connections (1 to each other node he is listening sync events from) instead of a unique connection to the MongoDB or redis instance.

**Comment by daffl** [comment]
Closing since the latest version makes it fairly easy to create [custom adapters](https://github.com/feathersjs-ecosystem/feathers-sync#writing-custom-adapters).
