### ISSUE TITLE
Add support for DynamoDB (AmazonAWS)

### ISSUE THREAD

**Issue by abalad** [feathersjs-ecosystem/feathers-sync#67]
The possibility of adding support for amazon's DynamoDB? Since applications deployed there, if you do not use their own NOSQL Storage service, you must upload a new EC2 instance with MongoDB

**Comment by clockworked247** [comment]
+1

**Comment by 1beb** [comment]
+1

**Comment by gauthieramano** [comment]
+1

**Comment by 1beb** [comment]
https://github.com/jus101/feathers-dynamodb There's this too. Haven't tried it. Was waiting for something official.

**Comment by daffl** [comment]
All database adapters are community efforts, happy to support anybody who is willing to take it on or commission development.

I also realized that this repository is probably not the right spot for this issue since DynamoDB is a NoSQL storage and not a message broker which is what `feathers-sync` is about.
