### ISSUE TITLE
Question about scalability

### ISSUE THREAD

**Issue by ashconnell** [feathersjs-ecosystem/feathers-sync#93]
Please correct me if I'm wrong but this is how I understand the implementation:

If feathers-sync sends every event to every server instance then doesn't that mean your instances get diminishing returns as you continue to scale?

As an example, say I have 2 small instances, each instance can handle around 500 active users at once. Let's say each user is creating a document every 5 seconds. This means every 5 seconds 500 events are published per instance, and 500 events are received by each instance. This seems feasible.

But now let's ramp this up to 10 instances, again with each having 500 users and each user creating a document once every 5 seconds. This time, every 5 seconds 500 events are published per instance but 4500 events are received from the other instances. This is quite a heavy load.

One option here is to then reduce the amount of users each instance handles, to allow more computational power for the incoming events. But this can only go so far before it's 1 server handling a single user and millions of events per second.

Is this an accurate depiction of how feathers would scale?

**Comment by daffl** [comment]
There are Feathers APIs that handle several million requests a day and performing quite well. At millions of requests/events per second you would be looking at a massive scale (say Google or Facebook) so I'm not sure if I can make any statements about that. Happy to discuss specifics with a realistic application benchmark but chances are that Feathers probably won't be the first bottleneck you'll encounter (because it really isn't doing that much).
